### ISSUE TITLE
Mapping to state names in geoplot_data.contiguous_usa

### ISSUE THREAD

**Issue by dhimmel** [ResidentMario/geoplot#51] opened 2017-12-20 20:32 UTC
I recently used geoplot to create a map of mesothelioma mortality by state in the contiguous United States ([notebook](https://github.com/dhimmel/mesothelioma/blob/886f3a0779c9cb6cb051e22c2f72c5be1e348087/mesothelioma.ipynb)).

The `geometry` information is obtained from the `contiguous_usa` dataset of the [quilt dataset](https://quiltdata.com/package/ResidentMario/geoplot_data). Each state is identified by its `adm1_code`. I couldn't find a mapping of `adm1_code` to state name. Is there a resource that defines these level 1 administrative codes?

Anyways, I took the state names from the [Choropleth subplots example](https://residentmario.github.io/geoplot/examples/nyc-parking-tickets.html), doing the following:

```python
contiguous_usa['State'] = [
    'Minnesota', 'Montana', 'North Dakota', 'Idaho', 'Washington', 'Arizona',
    'California', 'Colorado', 'Nevada', 'New Mexico', 'Oregon', 'Utah', 'Wyoming',
    'Arkansas', 'Iowa', 'Kansas', 'Missouri', 'Nebraska', 'Oklahoma', 'South Dakota',
    'Louisiana', 'Texas', 'Connecticut', 'Massachusetts', 'New Hampshire',
    'Rhode Island', 'Vermont', 'Alabama', 'Florida', 'Georgia', 'Mississippi',
    'South Carolina', 'Illinois', 'Indiana', 'Kentucky', 'North Carolina', 'Ohio',
    'Tennessee', 'Virginia', 'Wisconsin', 'West Virginia', 'Delaware', 'District of Columbia',
    'Maryland', 'New Jersey', 'New York', 'Pennsylvania', 'Maine', 'Michigan',
]
```

I hate to assign by position like this because it's so error prone. It would be nice to add a `state` column to the `contiguous_usa` dataset, so users don't have to perform this fragile manual step. Or at the minimum, use a dictionary to map `adm1_code` to `state` in examples, so at least most issues that arise will be more apparent.

More generally, where are good places to receive geometry data? I wasn't sure how limited users are to the quilt datasets? Say for example, I wanted to remake the plot with Alaska and Hawaii? I guess what I'm interested in is these geometry polygons for all administrative areas.

**Comment by ResidentMario** [comment] 2017-12-22 16:26
This was actually due to an oversight when I was preparing the default data, I forgot to correct this standing issue. I will fix this the next time I patch the example datasets.

> More generally, where are good places to receive geometry data? I wasn't sure how limited users are to the quilt datasets?

I would recommend *against* using the Quilt dataset in practice, it's just a default package that I prepared to make the online examples reproducible. You can find plenty of GeoJSON or Shapefile datasets online to fit whatever needs you have, no need to rely on my example data specifically.

What are good places to get geometry data? That depends a lot on the domain you're working in. I usually just do a Google search with "geojson" or "shapefile" appended to the end.

> Say for example, I wanted to remake the plot with Alaska and Hawaii?

I excluded those from the example plots because `geoplot` doesn't formally support insets But you can do that yourself by manufacturing Alaska and Hawaii where you want them in the underlying data: scaled versions of the two states in the bottom left corner, for example.

**Comment by ResidentMario** [comment] 2017-12-23 21:26
I've updated the quilt data package to include the states, so closing this one out now.

**Closed by ResidentMario** 2017-12-23 21:26 UTC

**Comment by dhimmel** [comment] 2017-12-23 21:29
Thanks @ResidentMario!

Excited for the next time I need to geoplot and get to explore more features!
